/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
  }
}
